install.packages("shiny",clean=T)
install.packages("randomForest",clean=T)
install.packages("Rook",clean=T)
install.packages("rpart",clean=T)
install.packages("rattle",clean=T)
install.packages("rpart.plot",clean=T)
print("All packages installed...")